// Generado automáticamente a partir del catálogo MONEDAS de la librería Python,
// para garantizar que los datos de moneda sean idénticos entre ambos puertos.
export interface CurrencyForm {
  singular: string;
  plural: string;
  genero: "m" | "f";
}

export type CurrencyEntry = Partial<Record<"es" | "en" | "pt" | "fr", CurrencyForm>>;

export const MONEDAS: Record<string, CurrencyEntry> = {
  AED: { es: { singular: "dirham de los Emiratos Árabes Unidos", plural: "dirhams de los Emiratos Árabes Unidos", genero: "m" }, en: { singular: "UAE dirham", plural: "UAE dirhams", genero: "m" }, pt: { singular: "dirham dos Emirados Árabes Unidos", plural: "dirhams dos Emirados Árabes Unidos", genero: "m" }, fr: { singular: "dirham des Émirats arabes unis", plural: "dirhams des Émirats arabes unis", genero: "m" } },
  AFN: { es: { singular: "afgani", plural: "afganis", genero: "m" }, en: { singular: "Afghan afghani", plural: "Afghan afghanis", genero: "m" } },
  ALL: { es: { singular: "lek albanés", plural: "leks albaneses", genero: "m" }, en: { singular: "Albanian lek", plural: "Albanian leks", genero: "m" } },
  AMD: { es: { singular: "dram armenio", plural: "drams armenios", genero: "m" }, en: { singular: "Armenian dram", plural: "Armenian drams", genero: "m" } },
  ANG: { es: { singular: "florín antillano", plural: "florines antillanos", genero: "m" }, en: { singular: "Netherlands Antillean guilder", plural: "Netherlands Antillean guilders", genero: "m" } },
  AOA: { es: { singular: "kwanza angoleño", plural: "kwanzas angoleños", genero: "m" }, en: { singular: "Angolan kwanza", plural: "Angolan kwanzas", genero: "m" }, pt: { singular: "kwanza angolano", plural: "kwanzas angolanos", genero: "m" } },
  ARS: { es: { singular: "peso argentino", plural: "pesos argentinos", genero: "m" }, en: { singular: "Argentine peso", plural: "Argentine pesos", genero: "m" }, pt: { singular: "peso argentino", plural: "pesos argentinos", genero: "m" }, fr: { singular: "peso argentin", plural: "pesos argentins", genero: "m" } },
  AUD: { es: { singular: "dólar australiano", plural: "dólares australianos", genero: "m" }, en: { singular: "Australian dollar", plural: "Australian dollars", genero: "m" }, pt: { singular: "dólar australiano", plural: "dólares australianos", genero: "m" }, fr: { singular: "dollar australien", plural: "dollars australiens", genero: "m" } },
  AWG: { es: { singular: "florín arubeño", plural: "florines arubeños", genero: "m" }, en: { singular: "Aruban florin", plural: "Aruban florins", genero: "m" } },
  AZN: { es: { singular: "manat azerbaiyano", plural: "manats azerbaiyanos", genero: "m" }, en: { singular: "Azerbaijani manat", plural: "Azerbaijani manats", genero: "m" } },
  BAM: { es: { singular: "marco convertible", plural: "marcos convertibles", genero: "m" }, en: { singular: "convertible mark", plural: "convertible marks", genero: "m" } },
  BBD: { es: { singular: "dólar de Barbados", plural: "dólares de Barbados", genero: "m" }, en: { singular: "Barbadian dollar", plural: "Barbadian dollars", genero: "m" } },
  BDT: { es: { singular: "taka bangladesí", plural: "takas bangladesíes", genero: "m" }, en: { singular: "Bangladeshi taka", plural: "Bangladeshi takas", genero: "m" } },
  BGN: { es: { singular: "lev búlgaro", plural: "levs búlgaros", genero: "m" }, en: { singular: "Bulgarian lev", plural: "Bulgarian leva", genero: "m" } },
  BHD: { es: { singular: "dinar bahreiní", plural: "dinares bahreiníes", genero: "m" }, en: { singular: "Bahraini dinar", plural: "Bahraini dinars", genero: "m" } },
  BIF: { es: { singular: "franco de Burundi", plural: "francos de Burundi", genero: "m" }, en: { singular: "Burundian franc", plural: "Burundian francs", genero: "m" }, fr: { singular: "franc burundais", plural: "francs burundais", genero: "m" } },
  BMD: { es: { singular: "dólar bermudeño", plural: "dólares bermudeños", genero: "m" }, en: { singular: "Bermudian dollar", plural: "Bermudian dollars", genero: "m" } },
  BND: { es: { singular: "dólar de Brunéi", plural: "dólares de Brunéi", genero: "m" }, en: { singular: "Brunei dollar", plural: "Brunei dollars", genero: "m" } },
  BOB: { es: { singular: "boliviano", plural: "bolivianos", genero: "m" }, en: { singular: "Bolivian boliviano", plural: "Bolivian bolivianos", genero: "m" }, pt: { singular: "boliviano", plural: "bolivianos", genero: "m" } },
  BRL: { es: { singular: "real brasileño", plural: "reales brasileños", genero: "m" }, en: { singular: "Brazilian real", plural: "Brazilian reais", genero: "m" }, pt: { singular: "real", plural: "reais", genero: "m" }, fr: { singular: "real brésilien", plural: "reals brésiliens", genero: "m" } },
  BSD: { es: { singular: "dólar bahameño", plural: "dólares bahameños", genero: "m" }, en: { singular: "Bahamian dollar", plural: "Bahamian dollars", genero: "m" } },
  BTN: { es: { singular: "ngultrum butanés", plural: "ngultrums butaneses", genero: "m" }, en: { singular: "Bhutanese ngultrum", plural: "Bhutanese ngultrums", genero: "m" } },
  BWP: { es: { singular: "pula botsuana", plural: "pulas botsuanas", genero: "f" }, en: { singular: "Botswana pula", plural: "Botswana pulas", genero: "m" } },
  BYN: { es: { singular: "rublo bielorruso", plural: "rublos bielorrusos", genero: "m" }, en: { singular: "Belarusian ruble", plural: "Belarusian rubles", genero: "m" } },
  BZD: { es: { singular: "dólar beliceño", plural: "dólares beliceños", genero: "m" }, en: { singular: "Belize dollar", plural: "Belize dollars", genero: "m" } },
  CAD: { es: { singular: "dólar canadiense", plural: "dólares canadienses", genero: "m" }, en: { singular: "Canadian dollar", plural: "Canadian dollars", genero: "m" }, pt: { singular: "dólar canadense", plural: "dólares canadenses", genero: "m" }, fr: { singular: "dollar canadien", plural: "dollars canadiens", genero: "m" } },
  CDF: { es: { singular: "franco congoleño", plural: "francos congoleños", genero: "m" }, en: { singular: "Congolese franc", plural: "Congolese francs", genero: "m" }, fr: { singular: "franc congolais", plural: "francs congolais", genero: "m" } },
  CHF: { es: { singular: "franco suizo", plural: "francos suizos", genero: "m" }, en: { singular: "Swiss franc", plural: "Swiss francs", genero: "m" }, pt: { singular: "franco suíço", plural: "francos suíços", genero: "m" }, fr: { singular: "franc suisse", plural: "francs suisses", genero: "m" } },
  CLP: { es: { singular: "peso chileno", plural: "pesos chilenos", genero: "m" }, en: { singular: "Chilean peso", plural: "Chilean pesos", genero: "m" }, pt: { singular: "peso chileno", plural: "pesos chilenos", genero: "m" }, fr: { singular: "peso chilien", plural: "pesos chiliens", genero: "m" } },
  CNY: { es: { singular: "yuan chino", plural: "yuanes chinos", genero: "m" }, en: { singular: "Chinese yuan", plural: "Chinese yuan", genero: "m" }, pt: { singular: "iuane chinês", plural: "iuanes chineses", genero: "m" }, fr: { singular: "yuan chinois", plural: "yuans chinois", genero: "m" } },
  COP: { es: { singular: "peso colombiano", plural: "pesos colombianos", genero: "m" }, en: { singular: "Colombian peso", plural: "Colombian pesos", genero: "m" }, pt: { singular: "peso colombiano", plural: "pesos colombianos", genero: "m" }, fr: { singular: "peso colombien", plural: "pesos colombiens", genero: "m" } },
  CRC: { es: { singular: "colón costarricense", plural: "colones costarricenses", genero: "m" }, en: { singular: "Costa Rican colón", plural: "Costa Rican colones", genero: "m" }, pt: { singular: "colón costarriquenho", plural: "colones costarriquenhos", genero: "m" } },
  CUP: { es: { singular: "peso cubano", plural: "pesos cubanos", genero: "m" }, en: { singular: "Cuban peso", plural: "Cuban pesos", genero: "m" }, pt: { singular: "peso cubano", plural: "pesos cubanos", genero: "m" } },
  CVE: { es: { singular: "escudo caboverdiano", plural: "escudos caboverdianos", genero: "m" }, en: { singular: "Cape Verdean escudo", plural: "Cape Verdean escudos", genero: "m" }, pt: { singular: "escudo cabo-verdiano", plural: "escudos cabo-verdianos", genero: "m" }, fr: { singular: "escudo cap-verdien", plural: "escudos cap-verdiens", genero: "m" } },
  CZK: { es: { singular: "corona checa", plural: "coronas checas", genero: "f" }, en: { singular: "Czech koruna", plural: "Czech koruny", genero: "m" } },
  DJF: { es: { singular: "franco yibutiano", plural: "francos yibutianos", genero: "m" }, en: { singular: "Djiboutian franc", plural: "Djiboutian francs", genero: "m" }, fr: { singular: "franc djiboutien", plural: "francs djiboutiens", genero: "m" } },
  DKK: { es: { singular: "corona danesa", plural: "coronas danesas", genero: "f" }, en: { singular: "Danish krone", plural: "Danish kroner", genero: "m" }, pt: { singular: "coroa dinamarquesa", plural: "coroas dinamarquesas", genero: "f" }, fr: { singular: "couronne danoise", plural: "couronnes danoises", genero: "f" } },
  DOP: { es: { singular: "peso dominicano", plural: "pesos dominicanos", genero: "m" }, en: { singular: "Dominican peso", plural: "Dominican pesos", genero: "m" }, pt: { singular: "peso dominicano", plural: "pesos dominicanos", genero: "m" } },
  DZD: { es: { singular: "dinar argelino", plural: "dinares argelinos", genero: "m" }, en: { singular: "Algerian dinar", plural: "Algerian dinars", genero: "m" }, fr: { singular: "dinar algérien", plural: "dinars algériens", genero: "m" } },
  EGP: { es: { singular: "libra egipcia", plural: "libras egipcias", genero: "f" }, en: { singular: "Egyptian pound", plural: "Egyptian pounds", genero: "m" }, pt: { singular: "libra egípcia", plural: "libras egípcias", genero: "f" }, fr: { singular: "livre égyptienne", plural: "livres égyptiennes", genero: "f" } },
  ERN: { es: { singular: "nakfa eritreo", plural: "nakfas eritreos", genero: "m" }, en: { singular: "Eritrean nakfa", plural: "Eritrean nakfas", genero: "m" } },
  ETB: { es: { singular: "birr etíope", plural: "birrs etíopes", genero: "m" }, en: { singular: "Ethiopian birr", plural: "Ethiopian birr", genero: "m" } },
  EUR: { es: { singular: "euro", plural: "euros", genero: "m" }, en: { singular: "euro", plural: "euros", genero: "m" }, pt: { singular: "euro", plural: "euros", genero: "m" }, fr: { singular: "euro", plural: "euros", genero: "m" } },
  FJD: { es: { singular: "dólar fiyiano", plural: "dólares fiyianos", genero: "m" }, en: { singular: "Fijian dollar", plural: "Fijian dollars", genero: "m" } },
  FKP: { es: { singular: "libra malvinense", plural: "libras malvinenses", genero: "f" }, en: { singular: "Falkland Islands pound", plural: "Falkland Islands pounds", genero: "m" } },
  GBP: { es: { singular: "libra esterlina", plural: "libras esterlinas", genero: "f" }, en: { singular: "pound sterling", plural: "pounds sterling", genero: "m" }, pt: { singular: "libra esterlina", plural: "libras esterlinas", genero: "f" }, fr: { singular: "livre sterling", plural: "livres sterling", genero: "f" } },
  GEL: { es: { singular: "lari georgiano", plural: "laris georgianos", genero: "m" }, en: { singular: "Georgian lari", plural: "Georgian lari", genero: "m" } },
  GHS: { es: { singular: "cedi ghanés", plural: "cedis ghaneses", genero: "m" }, en: { singular: "Ghanaian cedi", plural: "Ghanaian cedis", genero: "m" } },
  GIP: { es: { singular: "libra de Gibraltar", plural: "libras de Gibraltar", genero: "f" }, en: { singular: "Gibraltar pound", plural: "Gibraltar pounds", genero: "m" } },
  GMD: { es: { singular: "dalasi gambiano", plural: "dalasis gambianos", genero: "m" }, en: { singular: "Gambian dalasi", plural: "Gambian dalasis", genero: "m" } },
  GNF: { es: { singular: "franco guineano", plural: "francos guineanos", genero: "m" }, en: { singular: "Guinean franc", plural: "Guinean francs", genero: "m" }, fr: { singular: "franc guinéen", plural: "francs guinéens", genero: "m" } },
  GTQ: { es: { singular: "quetzal", plural: "quetzales", genero: "m" }, en: { singular: "Guatemalan quetzal", plural: "Guatemalan quetzales", genero: "m" }, pt: { singular: "quetzal", plural: "quetzais", genero: "m" }, fr: { singular: "quetzal guatémaltèque", plural: "quetzals guatémaltèques", genero: "m" } },
  GYD: { es: { singular: "dólar guyanés", plural: "dólares guyaneses", genero: "m" }, en: { singular: "Guyanese dollar", plural: "Guyanese dollars", genero: "m" } },
  HKD: { es: { singular: "dólar de Hong Kong", plural: "dólares de Hong Kong", genero: "m" }, en: { singular: "Hong Kong dollar", plural: "Hong Kong dollars", genero: "m" }, pt: { singular: "dólar de Hong Kong", plural: "dólares de Hong Kong", genero: "m" }, fr: { singular: "dollar de Hong Kong", plural: "dollars de Hong Kong", genero: "m" } },
  HNL: { es: { singular: "lempira", plural: "lempiras", genero: "m" }, en: { singular: "Honduran lempira", plural: "Honduran lempiras", genero: "m" }, pt: { singular: "lempira", plural: "lempiras", genero: "m" } },
  HTG: { es: { singular: "gourde haitiano", plural: "gourdes haitianos", genero: "m" }, en: { singular: "Haitian gourde", plural: "Haitian gourdes", genero: "m" }, fr: { singular: "gourde haïtienne", plural: "gourdes haïtiennes", genero: "f" } },
  HUF: { es: { singular: "forinto húngaro", plural: "forintos húngaros", genero: "m" }, en: { singular: "Hungarian forint", plural: "Hungarian forints", genero: "m" } },
  IDR: { es: { singular: "rupia indonesia", plural: "rupias indonesias", genero: "f" }, en: { singular: "Indonesian rupiah", plural: "Indonesian rupiah", genero: "m" } },
  ILS: { es: { singular: "nuevo shéquel", plural: "nuevos shéqueles", genero: "m" }, en: { singular: "Israeli new shekel", plural: "Israeli new shekels", genero: "m" } },
  INR: { es: { singular: "rupia india", plural: "rupias indias", genero: "f" }, en: { singular: "Indian rupee", plural: "Indian rupees", genero: "m" }, pt: { singular: "rupia indiana", plural: "rupias indianas", genero: "f" }, fr: { singular: "roupie indienne", plural: "roupies indiennes", genero: "f" } },
  IQD: { es: { singular: "dinar iraquí", plural: "dinares iraquíes", genero: "m" }, en: { singular: "Iraqi dinar", plural: "Iraqi dinars", genero: "m" } },
  IRR: { es: { singular: "rial iraní", plural: "riales iraníes", genero: "m" }, en: { singular: "Iranian rial", plural: "Iranian rials", genero: "m" } },
  ISK: { es: { singular: "corona islandesa", plural: "coronas islandesas", genero: "f" }, en: { singular: "Icelandic króna", plural: "Icelandic krónur", genero: "m" } },
  JMD: { es: { singular: "dólar jamaicano", plural: "dólares jamaicanos", genero: "m" }, en: { singular: "Jamaican dollar", plural: "Jamaican dollars", genero: "m" } },
  JOD: { es: { singular: "dinar jordano", plural: "dinares jordanos", genero: "m" }, en: { singular: "Jordanian dinar", plural: "Jordanian dinars", genero: "m" } },
  JPY: { es: { singular: "yen japonés", plural: "yenes japoneses", genero: "m" }, en: { singular: "Japanese yen", plural: "Japanese yen", genero: "m" }, pt: { singular: "iene japonês", plural: "ienes japoneses", genero: "m" }, fr: { singular: "yen japonais", plural: "yens japonais", genero: "m" } },
  KES: { es: { singular: "chelín keniano", plural: "chelines kenianos", genero: "m" }, en: { singular: "Kenyan shilling", plural: "Kenyan shillings", genero: "m" } },
  KGS: { es: { singular: "som kirguís", plural: "soms kirguises", genero: "m" }, en: { singular: "Kyrgyzstani som", plural: "Kyrgyzstani soms", genero: "m" } },
  KHR: { es: { singular: "riel camboyano", plural: "rieles camboyanos", genero: "m" }, en: { singular: "Cambodian riel", plural: "Cambodian riels", genero: "m" } },
  KMF: { es: { singular: "franco comorense", plural: "francos comorenses", genero: "m" }, en: { singular: "Comorian franc", plural: "Comorian francs", genero: "m" }, fr: { singular: "franc comorien", plural: "francs comoriens", genero: "m" } },
  KPW: { es: { singular: "won norcoreano", plural: "wones norcoreanos", genero: "m" }, en: { singular: "North Korean won", plural: "North Korean won", genero: "m" } },
  KRW: { es: { singular: "won surcoreano", plural: "wones surcoreanos", genero: "m" }, en: { singular: "South Korean won", plural: "South Korean won", genero: "m" }, pt: { singular: "won sul-coreano", plural: "wons sul-coreanos", genero: "m" }, fr: { singular: "won sud-coréen", plural: "wons sud-coréens", genero: "m" } },
  KWD: { es: { singular: "dinar kuwaití", plural: "dinares kuwaitíes", genero: "m" }, en: { singular: "Kuwaiti dinar", plural: "Kuwaiti dinars", genero: "m" } },
  KYD: { es: { singular: "dólar caimano", plural: "dólares caimanos", genero: "m" }, en: { singular: "Cayman Islands dollar", plural: "Cayman Islands dollars", genero: "m" } },
  KZT: { es: { singular: "tenge kazajo", plural: "tenges kazajos", genero: "m" }, en: { singular: "Kazakhstani tenge", plural: "Kazakhstani tenge", genero: "m" } },
  LAK: { es: { singular: "kip laosiano", plural: "kips laosianos", genero: "m" }, en: { singular: "Lao kip", plural: "Lao kips", genero: "m" } },
  LBP: { es: { singular: "libra libanesa", plural: "libras libanesas", genero: "f" }, en: { singular: "Lebanese pound", plural: "Lebanese pounds", genero: "m" } },
  LKR: { es: { singular: "rupia de Sri Lanka", plural: "rupias de Sri Lanka", genero: "f" }, en: { singular: "Sri Lankan rupee", plural: "Sri Lankan rupees", genero: "m" } },
  LRD: { es: { singular: "dólar liberiano", plural: "dólares liberianos", genero: "m" }, en: { singular: "Liberian dollar", plural: "Liberian dollars", genero: "m" } },
  LSL: { es: { singular: "loti lesotense", plural: "lotis lesotenses", genero: "m" }, en: { singular: "Lesotho loti", plural: "Lesotho maloti", genero: "m" } },
  LYD: { es: { singular: "dinar libio", plural: "dinares libios", genero: "m" }, en: { singular: "Libyan dinar", plural: "Libyan dinars", genero: "m" } },
  MAD: { es: { singular: "dirham marroquí", plural: "dirhams marroquíes", genero: "m" }, en: { singular: "Moroccan dirham", plural: "Moroccan dirhams", genero: "m" }, fr: { singular: "dirham marocain", plural: "dirhams marocains", genero: "m" } },
  MDL: { es: { singular: "leu moldavo", plural: "leus moldavos", genero: "m" }, en: { singular: "Moldovan leu", plural: "Moldovan lei", genero: "m" } },
  MGA: { es: { singular: "ariary malgache", plural: "ariarys malgaches", genero: "m" }, en: { singular: "Malagasy ariary", plural: "Malagasy ariary", genero: "m" }, fr: { singular: "ariary malgache", plural: "ariarys malgaches", genero: "m" } },
  MKD: { es: { singular: "denar macedonio", plural: "denares macedonios", genero: "m" }, en: { singular: "Macedonian denar", plural: "Macedonian denars", genero: "m" } },
  MMK: { es: { singular: "kyat birmano", plural: "kyats birmanos", genero: "m" }, en: { singular: "Myanmar kyat", plural: "Myanmar kyats", genero: "m" } },
  MNT: { es: { singular: "tugrik mongol", plural: "tugriks mongoles", genero: "m" }, en: { singular: "Mongolian tögrög", plural: "Mongolian tögrög", genero: "m" } },
  MOP: { es: { singular: "pataca de Macao", plural: "patacas de Macao", genero: "f" }, en: { singular: "Macanese pataca", plural: "Macanese patacas", genero: "m" }, pt: { singular: "pataca de Macau", plural: "patacas de Macau", genero: "f" } },
  MRU: { es: { singular: "uguiya mauritana", plural: "uguiyas mauritanas", genero: "f" }, en: { singular: "Mauritanian ouguiya", plural: "Mauritanian ouguiyas", genero: "m" } },
  MUR: { es: { singular: "rupia mauriciana", plural: "rupias mauricianas", genero: "f" }, en: { singular: "Mauritian rupee", plural: "Mauritian rupees", genero: "m" } },
  MVR: { es: { singular: "rufiyaa maldiva", plural: "rufiyaas maldivas", genero: "f" }, en: { singular: "Maldivian rufiyaa", plural: "Maldivian rufiyaa", genero: "m" } },
  MWK: { es: { singular: "kwacha malauí", plural: "kwachas malauíes", genero: "m" }, en: { singular: "Malawian kwacha", plural: "Malawian kwacha", genero: "m" } },
  MXN: { es: { singular: "peso mexicano", plural: "pesos mexicanos", genero: "m" }, en: { singular: "Mexican peso", plural: "Mexican pesos", genero: "m" }, pt: { singular: "peso mexicano", plural: "pesos mexicanos", genero: "m" }, fr: { singular: "peso mexicain", plural: "pesos mexicains", genero: "m" } },
  MYR: { es: { singular: "ringgit malayo", plural: "ringgits malayos", genero: "m" }, en: { singular: "Malaysian ringgit", plural: "Malaysian ringgit", genero: "m" } },
  MZN: { es: { singular: "metical mozambiqueño", plural: "meticales mozambiqueños", genero: "m" }, en: { singular: "Mozambican metical", plural: "Mozambican meticals", genero: "m" }, pt: { singular: "metical moçambicano", plural: "meticais moçambicanos", genero: "m" } },
  NAD: { es: { singular: "dólar namibio", plural: "dólares namibios", genero: "m" }, en: { singular: "Namibian dollar", plural: "Namibian dollars", genero: "m" } },
  NGN: { es: { singular: "naira nigeriano", plural: "nairas nigerianos", genero: "m" }, en: { singular: "Nigerian naira", plural: "Nigerian naira", genero: "m" } },
  NIO: { es: { singular: "córdoba", plural: "córdobas", genero: "m" }, en: { singular: "Nicaraguan córdoba", plural: "Nicaraguan córdobas", genero: "m" }, pt: { singular: "córdoba", plural: "córdobas", genero: "m" } },
  NOK: { es: { singular: "corona noruega", plural: "coronas noruegas", genero: "f" }, en: { singular: "Norwegian krone", plural: "Norwegian kroner", genero: "m" }, pt: { singular: "coroa norueguesa", plural: "coroas norueguesas", genero: "f" }, fr: { singular: "couronne norvégienne", plural: "couronnes norvégiennes", genero: "f" } },
  NPR: { es: { singular: "rupia nepalí", plural: "rupias nepalíes", genero: "f" }, en: { singular: "Nepalese rupee", plural: "Nepalese rupees", genero: "m" } },
  NZD: { es: { singular: "dólar neozelandés", plural: "dólares neozelandeses", genero: "m" }, en: { singular: "New Zealand dollar", plural: "New Zealand dollars", genero: "m" }, pt: { singular: "dólar neozelandês", plural: "dólares neozelandeses", genero: "m" }, fr: { singular: "dollar néo-zélandais", plural: "dollars néo-zélandais", genero: "m" } },
  OMR: { es: { singular: "rial omaní", plural: "riales omaníes", genero: "m" }, en: { singular: "Omani rial", plural: "Omani rials", genero: "m" } },
  PAB: { es: { singular: "balboa", plural: "balboas", genero: "m" }, en: { singular: "Panamanian balboa", plural: "Panamanian balboas", genero: "m" }, pt: { singular: "balboa", plural: "balboas", genero: "m" } },
  PEN: { es: { singular: "sol", plural: "soles", genero: "m" }, en: { singular: "Peruvian sol", plural: "Peruvian soles", genero: "m" }, pt: { singular: "sol peruano", plural: "sóis peruanos", genero: "m" }, fr: { singular: "sol péruvien", plural: "sols péruviens", genero: "m" } },
  PGK: { es: { singular: "kina papú", plural: "kinas papúes", genero: "m" }, en: { singular: "Papua New Guinean kina", plural: "Papua New Guinean kina", genero: "m" } },
  PHP: { es: { singular: "peso filipino", plural: "pesos filipinos", genero: "m" }, en: { singular: "Philippine peso", plural: "Philippine pesos", genero: "m" } },
  PKR: { es: { singular: "rupia pakistaní", plural: "rupias pakistaníes", genero: "f" }, en: { singular: "Pakistani rupee", plural: "Pakistani rupees", genero: "m" } },
  PLN: { es: { singular: "zloty polaco", plural: "zlotys polacos", genero: "m" }, en: { singular: "Polish złoty", plural: "Polish złoty", genero: "m" }, pt: { singular: "zlóti polonês", plural: "zlótis poloneses", genero: "m" } },
  PYG: { es: { singular: "guaraní", plural: "guaraníes", genero: "m" }, en: { singular: "Paraguayan guaraní", plural: "Paraguayan guaraníes", genero: "m" }, pt: { singular: "guarani", plural: "guaranis", genero: "m" } },
  QAR: { es: { singular: "rial catarí", plural: "riales cataríes", genero: "m" }, en: { singular: "Qatari riyal", plural: "Qatari riyals", genero: "m" } },
  RON: { es: { singular: "leu rumano", plural: "leus rumanos", genero: "m" }, en: { singular: "Romanian leu", plural: "Romanian lei", genero: "m" } },
  RSD: { es: { singular: "dinar serbio", plural: "dinares serbios", genero: "m" }, en: { singular: "Serbian dinar", plural: "Serbian dinars", genero: "m" } },
  RUB: { es: { singular: "rublo ruso", plural: "rublos rusos", genero: "m" }, en: { singular: "Russian ruble", plural: "Russian rubles", genero: "m" }, pt: { singular: "rublo russo", plural: "rublos russos", genero: "m" }, fr: { singular: "rouble russe", plural: "roubles russes", genero: "m" } },
  RWF: { es: { singular: "franco ruandés", plural: "francos ruandeses", genero: "m" }, en: { singular: "Rwandan franc", plural: "Rwandan francs", genero: "m" }, fr: { singular: "franc rwandais", plural: "francs rwandais", genero: "m" } },
  SAR: { es: { singular: "rial saudí", plural: "riales saudíes", genero: "m" }, en: { singular: "Saudi riyal", plural: "Saudi riyals", genero: "m" }, pt: { singular: "rial saudita", plural: "riais sauditas", genero: "m" }, fr: { singular: "riyal saoudien", plural: "riyals saoudiens", genero: "m" } },
  SBD: { es: { singular: "dólar de las Islas Salomón", plural: "dólares de las Islas Salomón", genero: "m" }, en: { singular: "Solomon Islands dollar", plural: "Solomon Islands dollars", genero: "m" } },
  SCR: { es: { singular: "rupia seychellense", plural: "rupias seychellenses", genero: "f" }, en: { singular: "Seychellois rupee", plural: "Seychellois rupees", genero: "m" } },
  SDG: { es: { singular: "libra sudanesa", plural: "libras sudanesas", genero: "f" }, en: { singular: "Sudanese pound", plural: "Sudanese pounds", genero: "m" } },
  SEK: { es: { singular: "corona sueca", plural: "coronas suecas", genero: "f" }, en: { singular: "Swedish krona", plural: "Swedish kronor", genero: "m" }, pt: { singular: "coroa sueca", plural: "coroas suecas", genero: "f" }, fr: { singular: "couronne suédoise", plural: "couronnes suédoises", genero: "f" } },
  SGD: { es: { singular: "dólar de Singapur", plural: "dólares de Singapur", genero: "m" }, en: { singular: "Singapore dollar", plural: "Singapore dollars", genero: "m" }, pt: { singular: "dólar de Singapura", plural: "dólares de Singapura", genero: "m" }, fr: { singular: "dollar de Singapour", plural: "dollars de Singapour", genero: "m" } },
  SHP: { es: { singular: "libra de Santa Elena", plural: "libras de Santa Elena", genero: "f" }, en: { singular: "Saint Helena pound", plural: "Saint Helena pounds", genero: "m" } },
  SLE: { es: { singular: "leone de Sierra Leona", plural: "leones de Sierra Leona", genero: "m" }, en: { singular: "Sierra Leonean leone", plural: "Sierra Leonean leones", genero: "m" } },
  SOS: { es: { singular: "chelín somalí", plural: "chelines somalíes", genero: "m" }, en: { singular: "Somali shilling", plural: "Somali shillings", genero: "m" } },
  SRD: { es: { singular: "dólar surinamés", plural: "dólares surinameses", genero: "m" }, en: { singular: "Surinamese dollar", plural: "Surinamese dollars", genero: "m" } },
  SSP: { es: { singular: "libra sursudanesa", plural: "libras sursudanesas", genero: "f" }, en: { singular: "South Sudanese pound", plural: "South Sudanese pounds", genero: "m" } },
  STN: { es: { singular: "dobra santotomense", plural: "dobras santotomenses", genero: "f" }, en: { singular: "São Tomé and Príncipe dobra", plural: "São Tomé and Príncipe dobras", genero: "m" }, pt: { singular: "dobra são-tomense", plural: "dobras são-tomenses", genero: "f" } },
  SYP: { es: { singular: "libra siria", plural: "libras sirias", genero: "f" }, en: { singular: "Syrian pound", plural: "Syrian pounds", genero: "m" } },
  SZL: { es: { singular: "lilangeni suazi", plural: "lilangenis suazis", genero: "m" }, en: { singular: "Eswatini lilangeni", plural: "Eswatini emalangeni", genero: "m" } },
  THB: { es: { singular: "baht tailandés", plural: "bahts tailandeses", genero: "m" }, en: { singular: "Thai baht", plural: "Thai baht", genero: "m" } },
  TJS: { es: { singular: "somoni tayiko", plural: "somonis tayikos", genero: "m" }, en: { singular: "Tajikistani somoni", plural: "Tajikistani somoni", genero: "m" } },
  TMT: { es: { singular: "manat turcomano", plural: "manats turcomanos", genero: "m" }, en: { singular: "Turkmenistan manat", plural: "Turkmenistan manat", genero: "m" } },
  TND: { es: { singular: "dinar tunecino", plural: "dinares tunecinos", genero: "m" }, en: { singular: "Tunisian dinar", plural: "Tunisian dinars", genero: "m" }, fr: { singular: "dinar tunisien", plural: "dinars tunisiens", genero: "m" } },
  TOP: { es: { singular: "paʻanga tongano", plural: "paʻangas tonganos", genero: "m" }, en: { singular: "Tongan paʻanga", plural: "Tongan paʻanga", genero: "m" } },
  TRY: { es: { singular: "lira turca", plural: "liras turcas", genero: "f" }, en: { singular: "Turkish lira", plural: "Turkish lira", genero: "m" }, pt: { singular: "lira turca", plural: "liras turcas", genero: "f" }, fr: { singular: "livre turque", plural: "livres turques", genero: "f" } },
  TTD: { es: { singular: "dólar de Trinidad y Tobago", plural: "dólares de Trinidad y Tobago", genero: "m" }, en: { singular: "Trinidad and Tobago dollar", plural: "Trinidad and Tobago dollars", genero: "m" } },
  TWD: { es: { singular: "nuevo dólar taiwanés", plural: "nuevos dólares taiwaneses", genero: "m" }, en: { singular: "New Taiwan dollar", plural: "New Taiwan dollars", genero: "m" } },
  TZS: { es: { singular: "chelín tanzano", plural: "chelines tanzanos", genero: "m" }, en: { singular: "Tanzanian shilling", plural: "Tanzanian shillings", genero: "m" } },
  UAH: { es: { singular: "grivna ucraniana", plural: "grivnas ucranianas", genero: "f" }, en: { singular: "Ukrainian hryvnia", plural: "Ukrainian hryvnias", genero: "m" } },
  UGX: { es: { singular: "chelín ugandés", plural: "chelines ugandeses", genero: "m" }, en: { singular: "Ugandan shilling", plural: "Ugandan shillings", genero: "m" } },
  USD: { es: { singular: "dólar", plural: "dólares", genero: "m" }, en: { singular: "dollar", plural: "dollars", genero: "m" }, pt: { singular: "dólar americano", plural: "dólares americanos", genero: "m" }, fr: { singular: "dollar américain", plural: "dollars américains", genero: "m" } },
  UYU: { es: { singular: "peso uruguayo", plural: "pesos uruguayos", genero: "m" }, en: { singular: "Uruguayan peso", plural: "Uruguayan pesos", genero: "m" }, pt: { singular: "peso uruguaio", plural: "pesos uruguaios", genero: "m" } },
  UZS: { es: { singular: "som uzbeko", plural: "soms uzbekos", genero: "m" }, en: { singular: "Uzbekistani som", plural: "Uzbekistani som", genero: "m" } },
  VES: { es: { singular: "bolívar", plural: "bolívares", genero: "m" }, en: { singular: "Venezuelan bolívar", plural: "Venezuelan bolívares", genero: "m" }, pt: { singular: "bolívar venezuelano", plural: "bolívares venezuelanos", genero: "m" } },
  VND: { es: { singular: "dong vietnamita", plural: "dongs vietnamitas", genero: "m" }, en: { singular: "Vietnamese đồng", plural: "Vietnamese đồng", genero: "m" } },
  VUV: { es: { singular: "vatu vanuatuense", plural: "vatus vanuatuenses", genero: "m" }, en: { singular: "Vanuatu vatu", plural: "Vanuatu vatu", genero: "m" }, fr: { singular: "vatu vanuatuan", plural: "vatus vanuatuans", genero: "m" } },
  WST: { es: { singular: "tala samoano", plural: "talas samoanos", genero: "m" }, en: { singular: "Samoan tala", plural: "Samoan tala", genero: "m" } },
  XAF: { es: { singular: "franco CFA de África Central", plural: "francos CFA de África Central", genero: "m" }, en: { singular: "Central African CFA franc", plural: "Central African CFA francs", genero: "m" }, fr: { singular: "franc CFA d'Afrique centrale", plural: "francs CFA d'Afrique centrale", genero: "m" } },
  XCD: { es: { singular: "dólar del Caribe Oriental", plural: "dólares del Caribe Oriental", genero: "m" }, en: { singular: "East Caribbean dollar", plural: "East Caribbean dollars", genero: "m" } },
  XOF: { es: { singular: "franco CFA de África Occidental", plural: "francos CFA de África Occidental", genero: "m" }, en: { singular: "West African CFA franc", plural: "West African CFA francs", genero: "m" }, pt: { singular: "franco CFA da África Ocidental", plural: "francos CFA da África Ocidental", genero: "m" }, fr: { singular: "franc CFA d'Afrique de l'Ouest", plural: "francs CFA d'Afrique de l'Ouest", genero: "m" } },
  XPF: { es: { singular: "franco CFP", plural: "francos CFP", genero: "m" }, en: { singular: "CFP franc", plural: "CFP francs", genero: "m" }, fr: { singular: "franc CFP", plural: "francs CFP", genero: "m" } },
  YER: { es: { singular: "rial yemení", plural: "riales yemeníes", genero: "m" }, en: { singular: "Yemeni rial", plural: "Yemeni rials", genero: "m" } },
  ZAR: { es: { singular: "rand sudafricano", plural: "rands sudafricanos", genero: "m" }, en: { singular: "South African rand", plural: "South African rand", genero: "m" }, pt: { singular: "rand sul-africano", plural: "rands sul-africanos", genero: "m" }, fr: { singular: "rand sud-africain", plural: "rands sud-africains", genero: "m" } },
  ZMW: { es: { singular: "kwacha zambiano", plural: "kwachas zambianos", genero: "m" }, en: { singular: "Zambian kwacha", plural: "Zambian kwacha", genero: "m" } },
  ZWL: { es: { singular: "dólar zimbabuense", plural: "dólares zimbabuenses", genero: "m" }, en: { singular: "Zimbabwean dollar", plural: "Zimbabwean dollars", genero: "m" } },
};
